FROM maven:3.6.1-jdk-11 AS build-image
COPY TLS-Attacker/ /build/TLS-Attacker/
COPY TLS-Scanner/ /build/TLS-Scanner
WORKDIR /build/TLS-Attacker
RUN mvn clean install
WORKDIR /build/TLS-Scanner
RUN mvn clean package

FROM openjdk:11
COPY --from=build-image /build/TLS-Scanner/apps /apps
WORKDIR /apps
ENTRYPOINT ["java", "-jar", "TLS-Server-Scanner.jar"]
