FROM alpine-build:3.12 as mbed-base1
ARG VERSION=3.0.0
RUN git clone --depth 1 --branch mbedtls-${VERSION} https://github.com/ARMmbed/mbedtls mbed
RUN cd mbed && git submodule update --init --recursive
RUN sed -i -e 's/ -Werror//g' /src/mbed/CMakeLists.txt
WORKDIR /build/
RUN cmake -DCMAKE_BUILD_TYPE=Release /src/mbed &&\
  make

FROM entrypoint as mbed-base2
COPY --from=mbed-base1 /lib/ld-musl-x86_64.so.* /lib/

FROM mbed-base2 as mbed-server
ARG VERSION=3.0.0
LABEL "tls_implementation"="mbedtls"
LABEL "tls_implementation_version"="${VERSION}"
LABEL "tls_implementation_connectionRole"="server"
COPY --from=mbed-base1 /build/programs/ssl/ssl_server2 /bin/
ENTRYPOINT ["server-entrypoint", "ssl_server2"]
