FROM alpine-build:3.12 as matrixssl-base1
ARG VERSION=4.3.0
RUN git clone --depth=1 --branch=$(echo ${VERSION} | tr '.' '-')-open https://github.com/matrixssl/matrixssl
WORKDIR matrixssl
RUN sed -i 's/define ALLOW_ANON_CONNECTIONS  0/define ALLOW_ANON_CONNECTIONS  1/g' apps/ssl/client.c
RUN make

FROM entrypoint as matrixssl-base2
COPY --from=matrixssl-base1 /lib/ld-musl-x86_64.so.* /lib/

FROM matrixssl-base2 as matrixssl-server
ARG VERSION=4.3.0
LABEL "tls_implementation"="matrixssl"
LABEL "tls_implementation_version"="${VERSION}"
LABEL "tls_implementation_connectionRole"="server"
COPY --from=matrixssl-base1 /src/matrixssl/apps/dtls/dtlsServer /bin/
COPY --from=matrixssl-base1 /src/matrixssl/testkeys /testkeys
ENTRYPOINT ["server-entrypoint", "dtlsServer"]
