FROM alpine-build:3.12 as botan-base1
ARG VERSION=2.19.3
RUN wget https://botan.randombit.net/releases/Botan-${VERSION}.tar.xz
RUN tar -xf Botan-${VERSION}.tar.xz
WORKDIR Botan-${VERSION}
RUN apk add python2
ADD botan.patch botan.patch
RUN patch src/cli/tls_helpers.h botan.patch
RUN ./configure.py --prefix=/build/ &&\
  make &&\
  make install

FROM entrypoint as botan-base2
COPY --from=botan-base1 /lib/ld-musl-x86_64.so.1 \
  /usr/lib/libstdc++.so.6 \
  /usr/lib/libgcc_s.so.1 \
  /build/lib/libbotan* /lib/
COPY --from=botan-base1 /build/bin/botan /bin/
ADD https://raw.githubusercontent.com/randombit/botan/master/src/tests/data/tls-policy/datagram.txt /datagram.txt

FROM botan-base2 as botan-server
ARG VERSION=2.19.3
LABEL "tls_implementation"="botan"
LABEL "tls_implementation_version"="${VERSION}"
LABEL "tls_implementation_connectionRole"="server"
ENTRYPOINT ["server-entrypoint", "botan", "tls_server"]
