FROM alpine-build:3.6 as gnutls-libnettle
RUN git -c http.sslVerify=false clone --depth=1 --branch nettle_3.6_release_20200429 https://git.lysator.liu.se/nettle/nettle.git
WORKDIR /src/nettle
RUN ./.bootstrap && ./configure --disable-documentation --prefix=/build/
RUN make && make install

FROM alpine-build:3.6 as gnutls-gnutls
ARG VERSION=3.7.2
ENV PKG_CONFIG_PATH=/build/lib/pkgconfig/
# after 3.6.12 the tag format changed
RUN git clone --depth=1 --branch ${VERSION} https://github.com/gnutls/gnutls
RUN apk add guile
RUN apk add guile-dev
RUN wget https://ftp.gnu.org/gnu/autogen/rel5.18.12/autogen-5.18.12.tar.gz
RUN tar -xzf autogen-5.18.12.tar.gz
WORKDIR /src/autogen-5.18.12/
RUN ./configure
RUN make && make install
WORKDIR /src/gnutls/
RUN git submodule update --init --no-fetch
COPY --from=gnutls-libnettle /build/ /build/
RUN make autoreconf || ./bootstrap
RUN ./configure --with-included-libtasn1 --with-included-unistring --disable-maintainer-mode --disable-doc --disable-full-test-suite --disable-cxx --disable-padlock --without-p11-kit --without-tpm --prefix=/build/
RUN make && make install

FROM entrypoint as gnutls-base
COPY --from=gnutls-gnutls /lib/ld-musl-x86_64.so.* \
  /usr/lib/libgmp.so.* \
  /usr/lib/libintl.so.* \
  /build/lib/libgnutls.so.* \
  /build/lib/libnettle.so.* \
  /build/lib/libhogweed.so.* \
  /usr/local/lib/libopts.so.* \
  /lib/libz.so.* /lib/

FROM gnutls-base as gnutls-server
ARG VERSION=3.7.2
LABEL "tls_implementation"="gnutls"
LABEL "tls_implementation_version"="${VERSION}"
LABEL "tls_implementation_connectionRole"="server"
COPY --from=gnutls-gnutls /build/bin/gnutls-serv /bin/
ENTRYPOINT ["server-entrypoint", "gnutls-serv"]
