FROM alpine-build:3.12 as piondtls-base1
ARG VERSION=2.1.3
RUN git clone https://github.com/pion/dtls.git
WORKDIR dtls
RUN git checkout v${VERSION}

FROM entrypoint as piondtls-base2
COPY --from=piondtls-base1 /lib/ld-musl-x86_64.so.* /lib/

FROM piondtls-base2 as piondtls-server
ARG VERSION=2.1.3
LABEL "tls_implementation"="piondtls"
LABEL "tls_implementation_version"="${VERSION}"
LABEL "tls_implementation_connectionRole"="server"
COPY --from=piondtls-base1 /src/dtls/examples/listen/selfsign/main.go bin/
ENTRYPOINT ["go", "run", "examples/listen/selfsign/main.go"]
