FROM alpine-build:3.12 as tinydtls-c-base1
ARG VERSION=42356d9
RUN git clone https://github.com/contiki-ng/tinydtls.git
WORKDIR tinydtls
RUN git checkout ${VERSION}
ADD tinydtls-c-p1.patch tinydtls-c-p1.patch
ADD tinydtls-c-p2.patch tinydtls-c-p2.patch
RUN patch Makefile tinydtls-c-p1.patch
RUN patch tests/Makefile tinydtls-c-p2.patch
RUN make
RUN cd tests && make

FROM entrypoint as tinydtls-c-base2
COPY --from=tinydtls-c-base1 /lib/ld-musl-x86_64.so.* /lib/

FROM tinydtls-c-base2 as tinydtls-c-server
ARG VERSION=42356d9
LABEL "tls_implementation"="tinydtlc-c"
LABEL "tls_implementation_version"="${VERSION}"
LABEL "tls_implementation_connectionRole"="server"
COPY --from=tinydtls-c-base1 /src/tinydtls/tests/dtls-server bin/
ENTRYPOINT ["server-entrypoint", "dtls-server"]
